version: "3.9"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "
            python manage.py migrate --fake django_celery_results 0006
            python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=recipecollector.settings
      - DB_HOST=mongodb://mongodb:27017
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
      - DEBUG=1
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=devuser
      - MONGO_INITDB_ROOT_PASSWORD=changeme
      - MONGO_INITDB_DATABASE=devdb
    ports:
      - 27017:27017
    volumes:
      - dev-db-data:/data/db

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.7-alpine
    environment:
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./app:/app
    expose:
      - "15672"

  celery_worker:
    container_name: celery_worker
    build:
      context: .
      dockerfile: Dockerfile
    ports: []
    volumes:
      - ./app:/app
    environment:
      - DJANGO_SETTINGS_MODULE=recipecollector.settings
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq/
      - DB_HOST=mongodb://mongodb:27017
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
    depends_on:
      - app
      - rabbitmq
    command: sh -c "celery -A recipecollector worker --pool=prefork --concurrency=10 -E --loglevel=info"

  celery_beat:
    container_name: celery_beat
    build:
      context: .
      dockerfile: Dockerfile
    ports: []
    environment:
      - DJANGO_SETTINGS_MODULE=recipecollector.settings
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq/
      - DB_HOST=mongodb://mongodb:27017
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
    depends_on:
      - app
      - rabbitmq
      - celery_worker
    command: sh -c "celery -A recipecollector beat -s /vol/celery/celerybeat-schedule --loglevel=info"

volumes:
  dev-db-data:
