# Generated by Django 4.0.8 on 2023-01-19 07:27

import core.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveBigIntegerField(unique=True)),
                ('title', models.CharField(max_length=300)),
                ('ingredients', djongo.models.fields.ArrayField(model_container=core.models.Ingredient)),
            ],
        ),
    ]
