# Generated by Django 3.1.12 on 2023-01-24 14:21

import core.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveBigIntegerField(unique=True)),
                ('title', models.CharField(max_length=300)),
                ('process', models.TextField(default='')),
                ('ingredients', djongo.models.fields.ArrayField(model_container=core.models.Ingredient)),
            ],
        ),
    ]
